### PR TITLE
[TASK] allow 'iframe' config option to use interactive stats instead of static image

### PR DESCRIPTION
**Pull request by MarcProe**
## Description
Add an 'iframe' config option to allow embedding grafana stats

## Motivation and Context
Embedding the stats looks nicer than a static image

## How Has This Been Tested?
Here's a test site:
https://hopglass.freifunk-niersufer.de/meshviewer/#/de/map/14cc2097d3dc

## Checklist:

- [x] My code follows the code style of this project. (CI will test it anyway and also needs approval)
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (How?)

### CODE REVIEW

**Comment by genofire** [comment]
I think we are still happy without iframe #44.
We want a fast meshviewer which could handle a lot of nodes for the fast growing networks in these communities.

The preferred way is, to show a grafana rendered image with a link to grafana dashboard for this node.
Link here: https://multi.meshviewer.org/#/en/map/d46e0ed04678 (a little testsuite for much nodes)

(By the way, a ci generates for every PR also a instance on netlify https://deploy-preview-250--meshviewer.netlify.com/ ;D )

**Comment by xf-** [comment]
I removed this option on propose.
- Needs more RAM and CPU. Needed 11,5 secs to load stats on Moto Z with Chrome with WLAN. Compared with our meshviewer the image are no real delay on mobile.
- More problems with CORS
- Our meshviewer updates also detail view - Complete iframe rendering every minute
- It is hard to calculate the height. For example you have scrollbars and on mobile Landscape it is complicated to scroll away from iframe, because iframe gets the event.

Only way to integrate grafana with interaction would be to bootstrap grafana js and render the panels inside meshviewer. This also needs a lot of changes like update every minute. This would be a small implementation. Grafana loads 4.5 MB js (you have no compression on your server - 1 MB transferred with gzip).

BTW: your image example is to large - reduce the size (height & width) and you are able to read them.

**Comment by MarcProe** [comment]
While I am not quite sure why an optional configuration everybody is free not to use was removed, I acknowledge that I did not do my research proper. And thanks for the hint about the image size 😉.

**Comment by xf-** [comment]
Because most user don't understand the impact on slow devices like a middle class smartphone including the traffic (1,5 MB and without gzip 5 MB). Also Update every Minute, not able to navigate on Mobile devices.

**Comment by MarcProe** [comment]
Would it be a wanted feature to use something like [D3](https://github.com/d3/d3) to render a graph on client side?
A server component could provide a JSON file as data source, and the client would load that data and visualize with D3.

**Comment by xf-** [comment]
Like i wrote, it would be interesting as option Grafana native widget - no iframe, uses same instance. But d3 is also a large library (we only use small parts) and client (Middle class smartphone) needs to render it. What is big difference to Grafana PhantomJS renderer?
BTW: Grafana will replace PhantomJS someday because it is unmaintained. A nice solution would be SVG image.

**Comment by MarcProe** [comment]
My goal would rather be to have something interactive rather than a still image. D3 is [~70K](https://d3js.org/d3.v5.min.js), with some modules maybe 100k worst case. Maybe I'll give it a try and see how it performs.

**Pull request closed without merging**
