### PR TITLE
[TASK] Simplify data processing

### PR DESCRIPTION
**Pull request by mwarning**
The data aggregation code is hard to reason about with its nested data structures. This change makes the code less complex and probably a bit faster.

### CODE REVIEW

**Comment by xf-** [comment]
This is more or less obsolete - for next milestone this code is already modified/gone.

**Comment by mwarning** [comment]
Where can this code be found?

**Comment by xf-** [comment]
correctly nowhere public

**Review by genofire — COMMENTED** [review]
It will work, but why we need it?
Just for reading?

We are building a new datahandling - could we close this PR for now?
(And you will take a new look over this code in a half-year)

**Comment by mwarning** [comment]
@genofire: it was intended to improve readability and code quality.

**Comment by genofire** [comment]
@mwarning thank you for your sympathy
(Hope you still send PR to improve meshviewer)

**Pull request closed without merging**
