### PR TITLE
add files to .gitignore

### PR DESCRIPTION
**Pull request by genofire**
config.json - if it is changes for the build of different communities
.sass-cache - it disturb me, too

### CODE REVIEW

**Comment by xf-** [comment]
.sass-cache is not present - is normally used by compass. We use only nodejs and no additional compass

config.json is in repo as example to and also used in travis. We use a separate branch
https://github.com/ffrgb/meshviewer/tree/ffrgb-config and rebase on develop.

**Comment by genofire** [comment]
Okay the .sass-cache is maybe from the old meshviewer.

But we has already a fork (and you did not made a fork) - so it is a little bit complicated.

**Comment by genofire** [comment]
maybe a move of the config.json to config-example.json or so?

**Comment by xf-** [comment]
grunt needs it for build in travis. Our custom stuff runs also through travis. It would be also possible to create a build and publish it as a release.

**Comment by genofire** [comment]
could travis copy the example file as a first step?

**Comment by genofire** [comment]
with config.json in gitignore it does not matter if config.json exists.
On a clone it will be delievered, on a change it has to be commit with force.

**Comment by xf-** [comment]
it can be copied, but i don't understand why a config.json is a problem. Once added changed will be tracked. We provide a fully functional version in git.

BTW: Do you use IRC?

**Comment by genofire** [comment]
Jep -> hackint (und xmpp) (hab meshviewer als channel aufgemacht)

**Comment by xf-** [comment]
resolved this in irc

**Pull request closed without merging**
