### PR TITLE
[TASK] Add newlines to uci commands

### PR DESCRIPTION
**Pull request by mwarning**
The uci commands need newlines.
- [x] yes

### CODE REVIEW

**Comment by mwarning** [comment]
Anyway, would this project be willing to make it easier to use the meshviewer for less gluon specific stuff?
Those uci commands are of no use to us and are confusing to the users.

Maybe some "gluon" : true setting? Better ideas are welcome.
I would like to use the map without to have to maintain my own fork...

**Comment by xf-** [comment]
A lot of bash console will submit first 4 lines instant. `;` separates commands

**Comment by mwarning** [comment]
True. Maybe we should replace the semicolons with newlines then?
It looks like an obfuscation attempt without the newlines. :-)

Imho, the style of the commands should be that of normal documentation.

**Comment by xf-** [comment]
I think c&p and submitting 4 the commands without checking isn't nice and also last persist command is missing. I don't see the advantage in newlines.

Result would be:
screenshot_20170903_213306

**Comment by mwarning** [comment]
Those (unintentional) line breaks look ugly. But that can be best dealt with style settings.

**Pull request closed without merging**
