### PR TITLE
[TASK] Use config.ffrgb.js as a default which can be replaced with config.js

### PR DESCRIPTION
**Pull request by MyIgel**
## Description
Moved the `config.js` file to `config.ffrgb.js` and added `config.js` to`.gitignore` to allow customization.

## Motivation and Context
To deploy the map to a server it is required to customize the `config.js` file for every community other than ffrgb. Currently that means that this file gets resettet every time it changes upstream and/or at least cause merge conflicts after a git pull. The current workarounds include hacking around by disabling git tracking or force pulling which is not feasible for automation which should only run when the repo changes.
To prevent these problems the `config.js` should be added to `.gitignore` so it does not get affected. The `config.ffrgb.js` will be used as a default fallback when no customized `config.js` could be found

At the end this small change would be a great improvement for any community using the meshviewer and would require no change for ffrgb. The functionality of a running git repo will be maintained.

## How Has This Been Tested?
As it only affects the configuration file, so besides of compiling it with and without a `config.js` no further tests are needed.

## Screenshots/links (if appropriate):
`-`

## Checklist:
- [x] My code follows the code style of this project. (CI will test it anyway and also needs approval)
- [x] My change requires a change to the documentation -- It does not seem to require any updates
- [x] I have updated the documentation accordingly -- No update needed

### CODE REVIEW

**Comment by rubo77** [comment]
Great! This would solve #267

**Comment by oszilloskop** [comment]
@MyIgel 
What about the file _[config.default.js](https://github.com/ffrgb/meshviewer/blob/develop/config.default.js)_?
Shouldn't this freely configurable configuration file also be added to .gitignore?

**Review by xf- — CHANGES_REQUESTED** [review]
This change will never be merged!

**Comment by christf** [comment]
@xf- Could you please share your reasons for not wanting to merge this?

**Comment by MyIgel** [comment]
Because of $reasons -> i will create a new PR :)

**Pull request closed without merging**
