### PR TITLE
[TASK] show linktype in lists

### PR DESCRIPTION
**Pull request by genofire**
In Node infobox, as Neightbours:
screenshot from 2017-11-09 20-19-38

In Linklist:
screenshot from 2017-11-09 20-19-55

### CODE REVIEW

**Comment by rubo77** [comment]
To save space, we could use a colour on the distance row instead an extra row for the type

**Comment by xf-** [comment]
Like i wrote in irc - no space on small devices. We already have issues in some cases
issue

**Comment by Zaunei** [comment]
+1 for Colors

**Comment by rubo77** [comment]
- If the link is via "other" make the distance i.e. "22m" blue and add a title-tag wich shows "other"
- If the link is via 5GHz make it orange
- 2.4GHz can stay black (or magenta)

**Comment by genofire** [comment]
@rubo77 batman did not show up, the frequence of wifi links.
ATM gluon could only publish `wifi`,`tunnel` (replaced by yanic with `vpn`), `other`.

Bad idea, to use more colors (to many color-legends) + what habbens wenn there is no distance -> color.

**Comment by rubo77** [comment]
How can there be no distance? But Put a "0m' there then.

I think, So at that place, there can be only "WiFi" or "other".

Other already has blue. So there is no extra colour needed.

WiFi links stay black.

So no legend needed, since the title tag also explains it additionally.

**Comment by rubo77** [comment]
I see: in the link list there can be type "fastd" which will be blue also "other".

If there is no distance, write "unknown"

**Comment by genofire** [comment]
The Linklist would work, but look not beatifule without space between the TQ and type:
screenshot from 2017-11-10 09-37-51

There is no space for `unknown` - the is no space for more then `10 m` without break:
screenshot from 2017-11-10 09-38-30
with a vpn without location is `0 m` not true.

---

ATM there is no type `fastd` - if yanic is possible to descide between tunnel, there would provide `vpn-fastd`, the meshviewer could work with it (different painting of vpn-links).  this would be longer then `other` .... i think it would not work eigther

**Comment by xf-** [comment]
And second node name is (nearly) gone

**Comment by rubo77** [comment]
you could write the distance without space: "58m" instead of "58 m".

And what about skipping the idea of en extra row for "type" completely and only use colours instead?

instead of distance "unknown" you could write "n.a." for not availlable

**Comment by rubo77** [comment]
meshviewer

**Pull request closed without merging**
